### PR TITLE
Wc shop size fit functionality

### PR DESCRIPTION
**Pull request by wcampbell91**

### CODE REVIEW

**Review by petestewart — APPROVED** [review]
~~Sure, why not?~~

**Review by petestewart — CHANGES_REQUESTED** [review]
Need Nate's js back!

**Review by MLogan1998 — CHANGES_REQUESTED** [review]
Add review js

**Review by MLogan1998 — APPROVED** [review]
Looks good to me

**Review by petestewart — APPROVED** [review]

**Review by petestewart — APPROVED** [review]

**Review by nathanieltylerowens — APPROVED** [review]
thanks for getting my JS back

**Pull request merged**
